CREATE TYPE symbol AS ENUM ('BTCUSDT');
CREATE TYPE side AS ENUM ('BUY', 'SELL');
CREATE TYPE trade_order_type AS ENUM ('MARKET', 'LIMIT');

CREATE TABLE IF NOT EXISTS test_orders
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol            symbol           NOT NUll,
    side              side             NOT NULL,
    trader_order_type trade_order_type NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    amount DECIMAL(30, 20) NOT NULL
);