DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'symbol') THEN
            CREATE TYPE symbol AS ENUM ('BTCUSDT');
        END IF;
    END
$$;

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'side') THEN
            CREATE TYPE side AS ENUM ('BUY', 'SELL');
        END IF;
    END
$$;

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_type') THEN
            CREATE TYPE order_type AS ENUM ('MARKET', 'LIMIT');
        END IF;
    END
$$;

CREATE TABLE IF NOT EXISTS orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol     symbol          NOT NUll,
    side       side            NOT NULL,
    order_type order_type      NOT NULL,
    price      DECIMAL(10, 2)  NOT NULL,
    amount     DECIMAL(30, 20) NOT NULL
);

CREATE TABLE IF NOT EXISTS pattern
(
    id SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS pattern_candle_directions
(
    pattern_id        INTEGER NOT NULL,
    position          INTEGER NOT NULL,
    candle_directions BOOLEAN NOT NULL,
    FOREIGN KEY (pattern_id) REFERENCES pattern (id),
    PRIMARY KEY (pattern_id, position)
);