DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'symbol') THEN
            CREATE TYPE symbol AS ENUM ('BTCUSDT');
        END IF;
    END
$$;

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'side') THEN
            CREATE TYPE side AS ENUM ('BUY', 'SELL');
        END IF;
    END
$$;

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_type') THEN
            CREATE TYPE order_type AS ENUM ('MARKET', 'LIMIT');
        END IF;
    END
$$;

CREATE TABLE IF NOT EXISTS test_orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol     VARCHAR         NOT NUll,
    side       VARCHAR         NOT NULL,
    order_type VARCHAR         NOT NULL,
    price      DECIMAL(10, 2)  NOT NULL,
    amount     DECIMAL(30, 20) NOT NULL
);